version: "3.6"
networks:
  espi-app-net:
    driver: "bridge"
    ipam:
      driver: default
services:
  espi-front:
    container_name: espi-frontend
    image: pesho02/espi-front:latest
    networks:
      - "espi-app-net"
    ports:
      - "4200:80"
  backend:
    container_name: espi-backend
    image: pesho02/espi-backend:latest
    networks:
      - "espi-app-net"
    restart: always
    ports:
      - "9000:9000"
    environment:
      TOKEN_SECRET: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlBlcGUiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNTE2MjM5MDIyLCJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsiYWRtaW4iLCJ1c2VyIiwibW9kIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6ImFkbWluIiwieC1oYXN1cmEtdXNlci1pZCI6IjEyMzQ1Njc4OTAiLCJ4LWhhc3VyYS1vcmctaWQiOiIxMjMiLCJ4LWhhc3VyYS1jdXN0b20iOiJjdXN0b20tdmFsdWUifSwiZXhwIjoxNjM4MDQ4MTgwMDM4fQ.PoHlLbOrLiKnO7LtwsHUsVB-dr7-mcQbwmz2F1Ywt38"
      PORT: 9000
      HOST: backend
      HASURA_URL: "http://graphql-engine:8080/v1/graphql"
      HASURA_ADMIN_PASSWORD: "myadminsecretkey"
      SITE_URL: "http://localhost:4200"
    depends_on:
      - postgres
      - graphql-engine
  postgres:
    image: postgres:12
    container_name: espi_postgress
    networks:
      - "espi-app-net"
    # hide in prod
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - 'E:\espi\db_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    container_name: espi_hasura
    image: hasura/graphql-engine:v2.0.0-alpha.5
    ports:
      - "8080:8080"
    networks:
      - "espi-app-net"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key": "alabala125kilooasdalabala125kilooasdalabala125kilooasd"}'
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: "false"
      TZ: Europe/Sofia
      BACKEND_URL: http://backend:9000
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  db_data:
# docker-compose down
# docker-compose up --build -d
