-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP TRIGGER IF EXISTS "set_sessions_start_time_from_referendums" ON "public"."referendums";DROP FUNCTION IF EXISTS "update_votting_sessions_start_time" CASCADE;
